http:
#################################################################### Routers
  routers:

    router-traefik:
      rule: "Host(`staucktion.com.tr`) && PathPrefix(`/traefik`) || HeaderRegexp(`Referer`, `(?i).*traefik.*`)"
      entryPoints: websecure
      service: api@internal
      tls:
        certResolver: lets
      middlewares:
        - middleware-strip-traefik
      priority: 3
      
    www-to-non-www:
      rule: "Host(`www.staucktion.com.tr`)"
      entryPoints: websecure
      service: api@internal
      tls:
        certResolver: lets
      middlewares:
        - www-to-non-www

    router-web-ui:
      rule: "Host(`staucktion.com.tr`)"
      entryPoints: websecure
      service: service-web-ui
      tls:
        certResolver: lets
      priority: 1

    router-web-api:
      rule: "Host(`staucktion.com.tr`) && PathPrefix(`/web-api`)"
      entryPoints: websecure
      service: service-web-api
      tls:
        certResolver: lets
      middlewares:
        - middleware-strip-web-api
      priority: 3

    router-bank-api:
      rule: "Host(`staucktion.com.tr`) && PathPrefix(`/bank-api`)"
      entryPoints: websecure
      service: service-bank-api
      tls:
        certResolver: lets
      middlewares:
        - middleware-strip-bank-api
      priority: 3

    router-bank-ui:
      rule: "Host(`staucktion.com.tr`) && PathPrefix(`/bank-ui`) || HeaderRegexp(`Referer`, `(?i).*bank-ui.*`)"
      entryPoints: websecure
      service: service-bank-ui
      tls:
        certResolver: lets
      middlewares:
        - middleware-strip-bank-ui
      priority: 2

#################################################################### Services
  services:

    service-web-ui:
      loadBalancer:
        servers:
          - url: "http://web-ui"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "6s"

    service-web-api:
      loadBalancer:
        servers:
          - url: "http://web-api"
        healthCheck:
          path: /health
          interval: "10s"
          timeout: "6s"

    service-bank-ui:
      loadBalancer:
        servers:
          - url: "http://bank-ui"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "6s"

    service-bank-api:
      loadBalancer:
        servers:
          - url: "http://bank-api"
        healthCheck:
          path: /health
          interval: "10s"
          timeout: "6s"

#################################################################### Middlewares
  middlewares:

    www-to-non-www:
      redirectRegex:
        regex: "^https?://www\\.(.*)"
        replacement: "https://$1"
        permanent: true

    middleware-strip-traefik:
      stripPrefix:
        prefixes:
          - "/traefik"

    middleware-strip-web-api:
      stripPrefix:
        prefixes:
          - "/web-api"

    middleware-strip-bank-ui:
      stripPrefix:
        prefixes:
          - "/bank-ui"

    middleware-strip-bank-api:
      stripPrefix:
        prefixes:
          - "/bank-api"